name: Sync with Bitbucket
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Sync from Bitbucket
        run: |
          # Evita errores si el remoto ya fue añadido en una ejecución fallida previa
          git remote remove bitbucket || true
          git remote add bitbucket https://bitbucket.org/spekpy/spekpy_release.git
          git fetch bitbucket --verbose
          git merge bitbucket/master --allow-unrelated-histories --no-edit
          git push origin master
